In [2]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Array Data Tipini Manuel Belirtmek
* Array'ın elemanlarının tipinin ne olacağını özellikle belirtebiliriz

In [3]:
x = np.array([1, 2, 3, 4.6])

In [4]:
x

array([1. , 2. , 3. , 4.6])

In [5]:
x = np.array([1, 2, 3, 4.6], dtype = "int32")

In [6]:
x

array([1, 2, 3, 4])

In [7]:
x = np.array([1, 2, 3, 4.6], dtype = "str")

In [8]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [15]:
x = np.array(["56"], dtype="int32")

In [17]:
x

array([56])

In [18]:
# "A" elemanı bir sayı olmadığı için int32'ye dönüştürülemez
x = np.array(["A"], dtype="int32")

ValueError: invalid literal for int() with base 10: 'A'