In [2]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Elemanları 0'lardan Oluşan Array Oluşturma

In [3]:
np.zeros(10).shape

(10,)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [6]:
np.zeros(10, str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

#### Elemanları 0'lardan Oluşan Multidimensional Array Oluşturmak

In [10]:
# 3 Row(Satır) ve 4 Column(Sütun)'u olan bir array oluşturma
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((2,3), bool)

array([[False, False, False],
       [False, False, False]])

In [12]:
np.zeros((4,4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.zeros((3, 4, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])