In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Belirtilen Elemandan Array Oluşturmak

In [3]:
np.full((4,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [4]:
np.full(4, 5)

array([5, 5, 5, 5])

In [6]:
arraySize = (4,5)
np.full(arraySize, "A")

array([['A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A']], dtype='<U1')

In [7]:
np.full(arraySize, 5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [8]:
np.full(arraySize, 5.2, dtype="int32")

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [9]:
# "5.2" str'den int'e çevrilemez
np.full(arraySize, "5.2", dtype="int32")

ValueError: invalid literal for int() with base 10: '5.2'

In [10]:
np.full(arraySize, float("5.2"), dtype="int32")

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])