In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Ardışık sayılardan Array Oluşturmak

In [3]:
for e in range(10):
    print(e)

0
1
2
3
4
5
6
7
8
9


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [6]:
np.arange(5,15,2)

array([ 5,  7,  9, 11, 13])

In [8]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])