In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Array İşlemleri

In [2]:
# * operatörü iki list arasında tanımsızdır hata verir
a = [1, 2]
b = [2, 3]
a*b

TypeError: can't multiply sequence by non-int of type 'list'

* List tile integer çarpılırsa ard arda concatenation yapar

In [4]:
[2, 4, 8] * 3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [5]:
# Yukarıdaki örnekle aynı işi yapar
[2,4,8] + [2,4,8] + [2,4,8] 

[2, 4, 8, 2, 4, 8, 2, 4, 8]

* `*` operatörü numpy'da tanımlıdır ve element-wise(elemanlar bazlı) çarpma yapar

In [8]:
x = np.array([1,2,3])
y = np.array([2,4,8])

x*y

array([ 2,  8, 24])

In [9]:
x+y

array([ 3,  6, 11])

In [10]:
x-y

array([-1, -2, -5])

* `element-wise` işlem yaptığı için çarpılan iki array'ın eleman sayısı aynı olmalıdır

In [11]:
z = np.array([2,3,4,5])

In [12]:
x*z

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [13]:
x*3

array([3, 6, 9])