In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Array Attribute'ları

##### Shape
* Array'ın row (satır) ve column (sütun) sayılarını verir

In [5]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
y = np.zeros((2,5,4))
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [11]:
x.shape

(2, 3)

In [12]:
y.shape

(2, 5, 4)

In [13]:
a = np.array([1,2,3])

In [14]:
a.shape

(3,)

##### ndim
* Arary'ın kaç boyutlu olduğunu verir

In [17]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [19]:
x.ndim

2

In [20]:
y.ndim

3

##### size
* Array'ın içinde kaç tane eleman olduğunu verir

In [22]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [25]:
x.size

6

In [26]:
y.size

40

##### dtype
Array'ın `type` 'ını verir

In [31]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
x.dtype

dtype('float64')