In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Reshaping 
* Reshape yaparken önemli olan nokta, `reshape` yaptığımız yapının yaptıktan sonraki yapıyla aynı eleman sayısına sahip olması. Bilakis `size`'ları aynı olacak

In [3]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a.shape

(10,)

In [5]:
a.ndim

1

In [6]:
a.size

10

In [7]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
a.reshape(2,5).size

10

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
b = a.reshape(2,5)

In [11]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
b.ndim

2

In [13]:
# Eleman sayısı tutmadığı için hata verecek
a.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

##### -1 ile Boyuta Karar Vermek

In [15]:
a.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

##### Yeni Boyut Eklemek

In [16]:
a = np.arange(1,11)

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a.shape

(10,)

In [19]:
a.ndim

1

In [20]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [21]:
a[np.newaxis, :].shape

(1, 10)

In [26]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [28]:
a[:, np.newaxis].shape

(10, 1)

* Veya `None` yazarakta yapabiliriz

In [30]:
a[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [31]:
a[:,None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])