In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Concatenation

In [2]:
a = np.array([1,2,3])

In [10]:
b = np.array([4,5,6])

In [11]:
a

array([1, 2, 3])

In [12]:
a.shape

(3,)

In [13]:
b.shape

(3,)

In [14]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [15]:
np.concatenate([b,a])

array([4, 5, 6, 1, 2, 3])

* Python `list`'lerini de numpy array'ları ile `concatenation`'a sokabiliriz

In [16]:
l = [10,20]

In [17]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6, 10, 20])

In [18]:
l = [9.5, 10, 11]

In [19]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  9.5, 10. , 11. ])

In [20]:
l = [10, 11, "12"]

In [21]:
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '10', '11', '12'], dtype='<U11')

* Python `tuple`'larını da numpy arrayları ile `concatenation`'a sokabiliriz

In [22]:
t = (10,20)

In [23]:
np.concatenate([a,b,t])

array([ 1,  2,  3,  4,  5,  6, 10, 20])

##### Size Mistmatch

In [41]:
c = np.array([5,6,7])

In [42]:
x = np.array([[1,2,3],
             [4,5,6]])

In [43]:
c.shape

(3,)

In [44]:
x.shape

(2, 3)

In [45]:
# Mistmatch Error
np.concatenate([c,x])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [47]:
# Kendisi ile concatenate olabilir
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([x,x], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([x,x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])