In [2]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Stack
* Stack mantığını yeni dimension ekleyip o dimension üzerinde concatenation yaparak da sağlayabiliriz

##### stack

In [5]:
a = np.array([1,2,3,4])

In [6]:
b = np.array([5,6,7,8])

In [7]:
a

array([1, 2, 3, 4])

In [8]:
b

array([5, 6, 7, 8])

In [9]:
a.shape

(4,)

In [10]:
a2 = a[None, :]

In [12]:
b2 = b[None, :]

In [13]:
a2

array([[1, 2, 3, 4]])

In [14]:
b2

array([[5, 6, 7, 8]])

In [15]:
np.concatenate([a2,b2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.concatenate([a2,b2], axis=1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [17]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

* Bunun aynısını `stack` ile daha kolay yapabiliriz

In [18]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])