In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Splitting

In [2]:
l = [10,20,30,40,50,60,70,80]

In [3]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [5]:
# [0,1], [2,3,4], [6,7]
np.split(l, [2,6]) # 2 ve 6'dan böl

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [6]:
# l = [10, 20, | 30, 40, 50, 60, | 70, 80]
#       0, 1 ,    2 , 3 , 4 , 5 ,   6 , 7 

In [7]:
np.split(l, [3,5,7])

[array([10, 20, 30]), array([40, 50]), array([60, 70]), array([80])]

In [8]:
a = np.split(l, [2,4])

In [9]:
a

[array([10, 20]), array([30, 40]), array([50, 60, 70, 80])]

In [10]:
type(a)

list

In [11]:
b = np.array([10, 20, 30, 40, 50, 60, 70, 80])

In [13]:
b

array([10, 20, 30, 40, 50, 60, 70, 80])

In [14]:
np.split(b, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [18]:
type(np.split(b, [2,6]))

list

In [19]:
np.split(b, [2,6])[0]

array([10, 20])

In [20]:
type(np.split(b, [2,6])[0])

numpy.ndarray

##### Split'in Sonucunu Birden Çok değişkene Eşitleme

In [21]:
a, b = (1,10)

In [22]:
a

1

In [23]:
b

10

In [24]:
x,y,z = np.split(l, [2,6])

In [25]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


In [26]:
type(x)

numpy.ndarray

##### vsplit

In [31]:
a = np.arange(16).reshape(4,4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
np.vsplit(a, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [35]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3]])

##### hsplit

In [36]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
np.hsplit(a, [1])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]