In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Sorting

In [8]:
a = np.array([20,32,5,30,10])

In [9]:
a

array([20, 32,  5, 30, 10])

In [10]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [11]:
a

array([20, 32,  5, 30, 10])

In [12]:
a.sort() # a'yı günceller

In [13]:
a

array([ 5, 10, 20, 30, 32])

##### argsort

In [14]:
a = np.array([3,1,6,5,4,2])

In [15]:
np.sort(a)

array([1, 2, 3, 4, 5, 6])

In [17]:
# Küçükten büyüğe sıralanmış elemanların indexlerini döndürür
idxs = np.argsort(a)

In [18]:
idxs

array([1, 5, 0, 4, 3, 2], dtype=int64)