In [1]:
import numpy as np

##### Creation Date:
##### January 29 2022
##### Created By Alperen KOLAMUC

#### Multidimensional Arrayların Elemanlarına Ulaşmak

In [26]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a[1]

array([ 6,  7,  8,  9, 10])

In [5]:
a[0,0]

1

In [6]:
a[0,2]

3

In [7]:
a[2,2]

13

In [8]:
b = np.arange(1,76).reshape(3,5,5)

In [11]:
b[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# 39 için
b[1][2][3] # b[birinci boyut][ikinci satır][üçüncü sütun]

39

In [17]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

           [0] [1] [2] [3] [4] 
     [0] [[ 1,  2,  3,  4,  5],
     --------------------------
     [1]  [ 6,  7,  8,  9, 10],
     [2]  [11, 12, 13, 14, 15],
     --------------------------
     [3]  [16, 17, 18, 19, 20]]

In [16]:
a[1:3] # 1 dahil 3 hariç [1:3)

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

           [0] [1]|[2]|[3] [4] 
     [0] [[ 1,  2,| 3,| 4,  5],
     -------------|---|--------
     [1]  [ 6,  7,| 8,| 9, 10],
     [2]  [11, 12,|13,|14, 15],
     -------------|---|--------
     [3]  [16, 17,|18,|19, 20]]

In [19]:
a[1:3,2]

array([ 8, 13])

           [0] [1]|[2] [3]|[4] 
     [0] [[ 1,  2,| 3,  4,| 5],
     -------------|-------|----
     [1]  [ 6,  7,| 8,  9,|10],
     [2]  [11, 12,|13, 14,|15],
     -------------|-------|----
     [3]  [16, 17,|18, 19,|20]]


In [24]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

##### Elemanları Değiştirebiliriz

In [27]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
a[1,1] = 10

In [29]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
# Arrayın veri tipi ne ise ona cast olur, array'ın veri tipini değiştirmez
a[1,1] = 20.61

In [31]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
a[1,1] = "30"

In [33]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
# "26.5" int'e dönmediği için hata verecek
a[1,1] = "26.5"

ValueError: invalid literal for int() with base 10: '26.5'

In [36]:
a[1,1] = float("26.5")

In [37]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 26,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [38]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6, 26,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [40]:
a[1::2]

array([[ 6, 26,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [41]:
a[:,3]

array([ 4,  9, 14, 19])

In [42]:
# Bütün rowları al ama sadece 3.indexteki column'u al
a[:,3].shape

(4,)

In [43]:
a[::2,3]

array([ 4, 14])