In [1]:
import numpy as np

##### Creation Date:
##### January 30 2022
##### Created By Alperen KOLAMUC

##### Fancy Indexing
* Şimdiye kadar hep belirli elemanları, belirli kesitlerdeki elemanları, veya belirli sayıda atlaya atlaya elemanları almayı öğrendik.`Fancy Index` ile belirli indexteki elemanları almayı göreceğiz

In [2]:
x = np.arange(1,15)

In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
idxs = [4,5,7,11]

In [5]:
# 4,5,7 ve 11. indexteki elemanları döndürür
x[idxs]

array([ 5,  6,  8, 12])

In [6]:
x[[1,3,10]]

array([ 2,  4, 11])

In [9]:
a = np.arange(12).reshape(3,4)

           [0]|[1]|[2]|[3]
     ---------|---|--------
     [0] [[ 0,| 1,| 2,  3],
     [1]  [ 4,| 5,| 6,  7],
     ---------|---|--------
     [2]  [ 8,| 9,|10, 11]]


In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a[0:2,1]

array([1, 5])

In [12]:
a[0:2,1].shape

(2,)

In [13]:
a = np.arange(20).reshape(4,5)

In [14]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
idx1 = [1,3,2]

In [16]:
idx2 = [3,0,2]

In [17]:
a[idx1, idx2] # a[[1,3,2], [3,0,2]]

array([ 8, 15, 12])