In [1]:
import numpy as np

##### Creation Date:
##### January 30 2022
##### Created By Alperen KOLAMUC

##### Subarray

In [2]:
a = np.arange(1, 21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
b = a[:2,:3]

In [5]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [7]:
b.ndim

2

In [8]:
b[0,0] = 100

In [9]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [11]:
a
# Biz a'dan aldığımız b değişkenindeki elemanı 100 yaptık ama aynı indexteki a elemanının da değeri 100 oldu. 
# Çünkü aynı "list"lerde ki gibi "=" operatörü ile adres referansı yaparız değer eşitlemesi değil. 
# Bir arraydan diğerini farklılaştırmak istiyorsak copy() metodunu kullanmalıyız

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

##### Copy
* `copy()` metod'unu kullanırsak `subarray`'ın değerinin değişmesi orjinal array'ı etkilemez

In [16]:
a = np.arange(1,21).reshape(4,5)

In [17]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
b = a[:2,:3].copy()

In [19]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [20]:
b[0,0] = 100

In [21]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])