In [1]:
import numpy as np

##### Creation Date:
##### January 30 2022
##### Created By Alperen KOLAMUC

##### Conditional Indexing

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [8]:
a[a<5]

array([1, 2, 3, 4])

In [9]:
a[[True,  True,  True,  True, False, False, False, False, False]]

array([1, 2, 3, 4])

In [10]:
filt= a < 3

In [11]:
filt

array([ True,  True, False, False, False, False, False, False, False])

In [12]:
a[filt]

array([1, 2])

In [13]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [15]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [16]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [17]:
a[a==b]

array([3, 4, 5, 7, 8])

In [18]:
# Broadcasting
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [20]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Normalde and or ile kurduğumuz mantığı numpy'da kullanamıyoruz
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [23]:
(a < 3) & (a > 5)

array([False, False, False, False, False, False, False, False, False])

##### Filtrenin Değili
`~` işareti değilini alır. Yapmak için AltGr + Ü sonrasında Space

In [31]:
a = np.arange(1,21).reshape(4,5)

In [32]:
filt = a < 5

In [33]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [34]:
a[filt]

array([1, 2, 3, 4])

In [35]:
a[~filt]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
~filt

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

##### Multidimensional Array'lerde Conditional Indexing

In [36]:
a = np.arange(1,21).reshape(4,5)

In [37]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [38]:
type(a)

numpy.ndarray

In [39]:
type( a < 7)

numpy.ndarray

In [40]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [41]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [42]:
a[a<7].shape

(6,)

In [43]:
a = np.array([1,2,3,None])

In [44]:
a

array([1, 2, 3, None], dtype=object)

In [45]:
a == None

array([False, False, False,  True])

In [46]:
a[a == None]

array([None], dtype=object)