In [1]:
import numpy as np

##### Creation Date:
##### January 30 2022
##### Created By Alperen KOLAMUC

##### sum
* Bütün elemanların toplamı

In [2]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
np.sum(a)

210

In [5]:
filt = a < 5

In [6]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [8]:
# Toplam 4 tane True var
np.sum(filt)

4

In [9]:
a[filt].sum()

10

##### Belirli Axis Üzerinde Toplama

In [10]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
# Her Column'u toplar 
np.sum(a , axis= 0)

array([34, 38, 42, 46, 50])

In [13]:
# Her Row'u toplar
np.sum(a, axis=1)

array([15, 40, 65, 90])