In [1]:
import numpy as np

##### Creation Date:
##### January 30 2022
##### Created By Alperen KOLAMUC

##### All
* Tüm elemanlar verilen şartı sağlıyor mu diye kontrol eder

In [2]:
a = np.arange(20).reshape(4,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [5]:
np.all(a>-1)

True

In [6]:
a>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
np.all(a>5)

False

In [8]:
a>4

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [9]:
np.all(a>4)

False

In [10]:
np.all(a>4, axis=1)

array([False,  True,  True,  True])

In [11]:
np.all(a>4, axis=0)

array([False, False, False, False, False])